# Generated by Django 5.2.10 on 2026-01-20 11:42

import django.utils.timezone
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dummys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dummy",
            name="description",
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
